# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

### FUNCTIONS ###

# command for writing command history out
function prompt_command {
    if [ $(($SECONDS - $LAST_HISTORY_WRITE)) -gt 60 ]; then
        history -a && history -c && history -r
        LAST_HISTORY_WRITE=$SECONDS
    fi
}

# from extensions.fcos.fr
install_sysext() {
  SYSEXT="${1}"
  URL="https://extensions.fcos.fr/extensions"
  sudo install -d -m 0755 -o 0 -g 0 /etc/sysupdate.${SYSEXT}.d
  sudo restorecon -RFv /etc/sysupdate.${SYSEXT}.d
  curl --silent --fail --location "${URL}/${SYSEXT}.conf" \
    | sudo tee "/etc/sysupdate.${SYSEXT}.d/${SYSEXT}.conf"
  sudo /usr/lib/systemd/systemd-sysupdate update --component "${SYSEXT}"
}


## export functions currently used
export -f prompt_command

# PATH helper functions - prevent duplicate entries
path_prepend() {
    [[ -d "$1" ]] && [[ ":$PATH:" != *":$1:"* ]] && PATH="$1:$PATH"
}
path_append() {
    [[ -d "$1" ]] && [[ ":$PATH:" != *":$1:"* ]] && PATH="$PATH:$1"
}

### ENV VARS ###

# Configuring command history
# https://www.digitalocean.com/community/tutorials/how-to-use-bash-history-commands-and-expansions-on-a-linux-vps
HISTTIMEFORMAT="%Y-%b-%d %T "
# https://www.happyassassin.net/2015/01/16/bash-history-with-multiple-sessions/
HISTSIZE=1048576
HISTFILESIZE=1048576
LAST_HISTORY_WRITE="$SECONDS"
PROMPT_COMMAND="$PROMPT_COMMAND"; prompt_command

# Define default LIBVIRT connection
export LIBVIRT_DEFAULT_URI=qemu:///system

# display git branch in prompt
# https://github.com/jimeh/git-aware-prompt
if [ -d ~/.bash/git-aware-prompt ]; then
    export GITAWAREPROMPT=~/.bash/git-aware-prompt
    source "${GITAWAREPROMPT}/main.sh"
fi

# colorize prompt, drop user@hostname portion because this is for my local account
export PS1="[\[\033[01;32m\]\u@\h \[\033[01;34m\]\w\[\033[00m\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]]\$ "

# indicate if we are in container
# of course jlebon has the better solution
# https://github.com/jlebon/files/blob/master/dotfiles/.bashrc#L222
__in_dockerenv=no
if [ -f /.dockerenv ] || [ -f /run/.containerenv ]; then
    __in_dockerenv=yes
fi

if [[ "$__in_dockerenv" == yes ]]; then
    export PS1="[\[\033[01;32m\]\u@\h \[$txtred\](container) \[\033[01;34m\]\w\[\033[00m\] \[$txtcyn\]\$git_branch\[$txtred\]\$git_dirty\[$txtrst\]]\$ "
fi

# for bpytop?
path_append "$HOME/.local/bin"

# OpenShift installer
export AWS_PROFILE=openshift-dev

# force a reasonable TERM
# helps with vim + tmux + line highlighting
export TERM=xterm-256color

### ALIASES

# User specific aliases and functions
alias sshq="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
alias scpq="scp -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
alias sshk="ssh -o PreferredAuthentications=keyboard-interactive,password -o PubkeyAuthentication=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

# Use 'sudo' with aliases
# http://askubuntu.com/a/22043
# This broke in F33
# https://unix.stackexchange.com/questions/627998/how-to-resolve-vi-internal-vim-alias-command-not-found
#alias sudo="sudo "

# use reflink=auto always
alias cp="cp --reflink=auto"

### ERRATA ###

# disable ctrl-s - suspend terminal
# https://stackoverflow.com/a/25391867
[[ $- == *i* ]] && stty -ixon

# Git tab completion
# https://github.com/git/git/blob/master/contrib/completion/git-completion.bash
if [ -f ~/git-completion.bash ]; then
    source ~/git-completion.bash
fi

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/var/home/miabbott/google-cloud-sdk/path.bash.inc' ]; then . '/var/home/miabbott/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/var/home/miabbott/google-cloud-sdk/completion.bash.inc' ]; then . '/var/home/miabbott/google-cloud-sdk/completion.bash.inc'; fi

# Claude
case "$(hostname)" in
    meatwad | pet)
        export CLAUDE_CODE_USE_VERTEX=1
        export CLOUD_ML_REGION=us-east5
        export ANTHROPIC_VERTEX_PROJECT_ID=itpc-gcp-core-pe-eng-claude
        ;;
    *)
        unset CLAUDE_CODE_USE_VERTEX
        unset CLOUD_ML_REGION
        unset ANTHROPIC_VERTEX_PROJECT_ID
esac

### bling.sh source start
test -f /usr/share/ublue-os/bling/bling.sh && source /usr/share/ublue-os/bling/bling.sh
### bling.sh source end

# remove the ls alias
if alias | grep "alias ls" > /dev/null; then
    unalias ls
fi

# ls -latr replacement function with eza
function ls() {
    if [ "$#" -ge 1 ] && [ "$1" = "-latr" ] && command -v eza >/dev/null; then
        # drop the passed flags
        shift
        eza -la --sort=old --reverse "$@"
    elif command -v eza >/dev/null; then
        command eza "$@"
    else
        command ls "$@"
    fi
}

# fix the use of podman inside the toolbox container
if [ -f /usr/local/bin/podman ] && [ -f /usr/local/bin/host-runner ]; then
    unalias podman
fi

path_prepend /sbin
path_prepend /usr/sbin
path_prepend /bin
path_prepend /usr/bin

if [ -d ~/workspaces/github.com/miabbott/files/bin ]; then
    path_prepend "$HOME/workspaces/github.com/miabbott/files/bin"
fi

if [ -f "$HOME/.local/bin/env" ]; then
. "$HOME/.local/bin/env"
fi
