apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 80-worker-kerberos
spec:
  config:
    ignition:
      version: 3.2.0
  extensions:
    - kerberos
